# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96aa569c864d7e811c26d28c3a1b10b28bab55d8a036a0920194684ba7bd073da58e85f45d8d51088c31e46b9d2d4ce1b2f43fca6a08054e883d6d3071185310

test:
  secret_key_base: e0f576da9a6814c4d58a0eb1c6ae6375de70a10e8377cedd3ee6a440314bd2672b319fc2beb230052a854abcbc5e6d128257cc58e3d25bf3cd5edf9b39546dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
